server:
  port: 9091
# Discovery Server Access
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

spring:
  application:
    name: autoindex
  data:
    elasticsearch:
      cluster-name: autoindex
      cluster-nodes: 
      properties:
        node:
          local: false
          data: true
        network:
          publish_host: ${ES_PUBLISH_HOST:}
        index:
          number_of_shards: 3
          replication_factor: 0
        path:
          logs: ${ES_HOME_DIR:.}/elasticsearch/log
          data: ${ES_HOME_DIR:.}/elasticsearch/data
        http:
          enabled: true
          port: 9092
